name: OpenTofu CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  opentofu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu-version: 'latest'

      - name: Init OpenTofu
        run: tofu init

      - name: Plan
        run: |
          tofu plan \
            -var "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var "AZURE_APP_ID=${{ secrets.AZURE_APP_ID }}" \
            -var "AZURE_APP_ID_SECRET=${{ secrets.AZURE_APP_ID_SECRET }}" \
            -var "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}"

      - name: Apply
        if: github.ref == 'refs/heads/master'
        run: |
          tofu apply -auto-approve \
            -var "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var "AZURE_APP_ID=${{ secrets.AZURE_APP_ID }}" \
            -var "AZURE_APP_ID_SECRET=${{ secrets.AZURE_APP_ID_SECRET }}" \
            -var "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}"