name: OpenTofu CI

on:
  push:
    branches:
      - master

jobs:
  opentofu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu-version: 'latest'

      - name: Init OpenTofu
        run: tofu init

      - name: Plan
        run: |
          tofu plan \
            -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var "client_id=${{ secrets.AZURE_APP_ID }}" \
            -var "client_secret=${{ secrets.AZURE_APP_ID_SECRET }}" \
            -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"

      - name: Apply
        if: github.ref == 'refs/heads/main'
        working-directory: opentofuinfra
        run: |
          tofu apply -auto-approve \
            -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var "client_id=${{ secrets.AZURE_APP_ID }}" \
            -var "client_secret=${{ secrets.AZURE_APP_ID_SECRET }}" \
            -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"