name: OpenTofu CI

on:
  push:
    branches:
      - master

jobs:
  opentofu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenTofu
        run: |
          curl -s https://get.opentofu.org/install.sh | bash
          echo "$HOME/.opentofu/bin" >> $GITHUB_PATH
          export PATH="$HOME/.opentofu/bin:$PATH"
          which tofu

      - name: Init OpenTofu
        run: tofu init

      - name: Plan
        run: |
          tofu plan \
            -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var "client_id=${{ secrets.AZURE_APP_ID }}" \
            -var "client_secret=${{ secrets.AZURE_APP_ID_SECRET }}" \
            -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"

      - name: Apply
        if: github.ref == 'refs/heads/main'
        working-directory: opentofuinfra
        run: |
          tofu apply -auto-approve \
            -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var "client_id=${{ secrets.AZURE_APP_ID }}" \
            -var "client_secret=${{ secrets.AZURE_APP_ID_SECRET }}" \
            -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"